version: '3'
services:
    
  keycloak:
    image: jboss/keycloak
    networks:
      - jugsummercampnet
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=postgres
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KEYCLOAK_USER=keycloak 
      - KEYCLOAK_PASSWORD=password
    expose:
      - 8080
    depends_on:
      - postgres

  postgres:
    image: postgres:10.3
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - jugsummercampnet
    environment: 
      - POSTGRES_DB=keycloak 
      - POSTGRES_USER=keycloak 
      - POSTGRES_PASSWORD=password
    command: '-c listen_addresses=*'
    volumes:
      - ./data/pg-data:/var/lib/postgresql/data

  nginx:
    image: nginx
    expose:
      - 8080
    ports:
      - 8889:8080
    networks:
      - jugsummercampnet
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - keycloak

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    environment:
      SERVER_NAME: kibana.foo.bar
      ELASTICSEARCH_URL: http://elastic:9200
    expose:
      - 5601
    ports: 
      - 5601:5601
    networks:
      - jugsummercampnet
    depends_on:
      - elastic

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/es-data:/usr/share/elasticsearch/data
    expose:
      - 9200
    ports: 
      - 9200:9200
    networks:
      - jugsummercampnet

  ingester:
    build: ./ingester
    networks:
      - jugsummercampnet
    environment: 
      - PORT=8080
      - ES_HOST=elastic
      - LOG_LEVEL=info
    expose:
      - 8080
    depends_on:
      - elastic

networks:
  jugsummercampnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.30/24